{"uuid": "73a52bbc-e2bd-4a5d-98b9-c66181c68c7d", "children": ["3efbdd3c-715e-4472-b9cf-19bd470693e6"], "befores": [{"name": "_xunit_setup_method_fixture_Test_testlogin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed\nfrom unknown error: web view not found\n  (Session info: chrome=113.0.5672.127)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x00D58893+48451]\n\t(No symbol) [0x00CEB8A1]\n\t(No symbol) [0x00BF5058]\n\t(No symbol) [0x00BDD073]\n\t(No symbol) [0x00C3DEBB]\n\t(No symbol) [0x00C4BFD3]\n\t(No symbol) [0x00C3A0B6]\n\t(No symbol) [0x00C17E08]\n\t(No symbol) [0x00C18F2D]\n\tGetHandleVerifier [0x00FB8E3A+2540266]\n\tGetHandleVerifier [0x00FF8959+2801161]\n\tGetHandleVerifier [0x00FF295C+2776588]\n\tGetHandleVerifier [0x00DE2280+612144]\n\t(No symbol) [0x00CF4F6C]\n\t(No symbol) [0x00CF11D8]\n\t(No symbol) [0x00CF12BB]\n\t(No symbol) [0x00CE4857]\n\tBaseThreadInitThunk [0x75E57D59+25]\n\tRtlInitializeExceptionChain [0x7700B74B+107]\n\tRtlClearBits [0x7700B6CF+191]\n\n", "trace": "  File \"E:\\python\\Python311\\Lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\python\\Python311\\Lib\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"E:\\python\\Python311\\Lib\\site-packages\\_pytest\\python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"E:\\python\\Python311\\Lib\\site-packages\\_pytest\\python.py\", line 788, in _call_with_optional_argument\n    func()\n  File \"E:\\project\\pytest-allure\\TestCases\\test_login.py\", line 29, in setup\n    self.driver.maximize_window()\n  File \"E:\\python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 592, in maximize_window\n    self.execute(command, None)\n  File \"E:\\python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\python\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1685890488898, "stop": 1685890505270}], "start": 1685890488898, "stop": 1685890505362}